<script src="bdesign/js/jquery.min.js" type="text/javascript"></script> 
<script src="bdesign/js/popper.min.js" type="text/javascript"></script> 
<script src="bdesign/js/bootstrap.min.js" type="text/javascript"></script> 
<script src="bdesign/js/functions.js" type="text/javascript"></script> 
<script src="bdesign/js/owl.cruiseousel.min.js" type="text/javascript"></script> 
<script src="bdesign/js/slick.js" type="text/javascript"></script> 
<script src="bdesign/js/swiper.min.js" type="text/javascript"></script> 
<script src="bdesign/js/main.js" type="text/javascript"></script> 
<script src="bdesign/js/jquery.fancybox.min.js" type="text/javascript"></script> 
<script src="bdesign/js/bootstrap-datepicker.min.js" type="text/javascript"></script> 
<script src="bdesign/js/jquery-ui.min.js" type="text/javascript"></script> 
<script src="bdesign/js/isotope.pkgd.min.js" type="text/javascript"></script> 
<script src="bdesign/js/imagesloaded.pkgd.min.js" type="text/javascript"></script>